// Brand registry for the per-prospect demo landing skins. Each car-brand demo is
// the SAME app under a different LANDING skin, resolved by URL path (/ford, /gm,
// /honda, …). The wordmarks/colours/marks are recreated brand cues for a demo —
// not the brands' official trademarked assets. Adding a brand = one entry here
// plus its favicon set in /public ({key}-icon.svg, {key}-favicon.ico,
// {key}-apple-icon.png), generated by scripts/gen-brand-favicons.

export type Brand = {
  key: string; // url slug + favicon basename
  name: string; // display name, e.g. "Ford"
  wordmark: string; // nav wordmark, e.g. "FORD"
  accent: string; // brand accent hex
  onAccent: string; // text colour on the accent button ("#000" | "#fff")
};

export const BRANDS = {
  ford: { key: "ford", name: "Ford", wordmark: "FORD", accent: "#0668E1", onAccent: "#fff" },
  gm: { key: "gm", name: "GM", wordmark: "GM", accent: "#0072CE", onAccent: "#fff" },
  honda: { key: "honda", name: "Honda", wordmark: "HONDA", accent: "#E40521", onAccent: "#fff" },
  toyota: { key: "toyota", name: "Toyota", wordmark: "TOYOTA", accent: "#EB0A1E", onAccent: "#fff" },
  bmw: { key: "bmw", name: "BMW", wordmark: "BMW", accent: "#0066B1", onAccent: "#fff" },
  volvo: { key: "volvo", name: "Volvo", wordmark: "VOLVO", accent: "#3D7AB8", onAccent: "#fff" },
  rivian: { key: "rivian", name: "Rivian", wordmark: "RIVIAN", accent: "#FED813", onAccent: "#000" },
} satisfies Record<string, Brand>;

export type BrandKey = keyof typeof BRANDS;

// string[] (not BrandKey[]) — these only feed route params, which are strings,
// so no cast is needed to stay honest about what Object.keys actually returns.
export const BRAND_KEYS = Object.keys(BRANDS);

// Real runtime-checked narrowing, the only sanctioned escape from `string` to a
// known key — so getBrand indexes BRANDS without an `as` cast.
export function isBrandKey(key: string): key is BrandKey {
  return Object.prototype.hasOwnProperty.call(BRANDS, key);
}

export function getBrand(key: string): Brand | null {
  return isBrandKey(key) ? BRANDS[key] : null;
}
