// One-off: parse the avatar-generation workflow output into a TS data module.
import { readFileSync, writeFileSync } from "node:fs";

const SRC = process.argv[2];
const OUT = "src/app/_components/personality-avatars-data.ts";

const raw = JSON.parse(readFileSync(SRC, "utf8"));
const batches = raw.result?.batches ?? raw.batches ?? [];

function decode(s) {
  return s
    .replaceAll("&lt;", "<")
    .replaceAll("&gt;", ">")
    .replaceAll("&quot;", '"')
    .replaceAll("&#39;", "'")
    .replaceAll("&apos;", "'")
    .replaceAll("&amp;", "&");
}

const BANNED = ["<defs", " id=", "<text", "<style", "<image", "<script", "url("];

const seen = new Set();
const list = [];
const map = {};
let rejected = 0;

for (const batch of batches) {
  for (const a of batch?.avatars ?? []) {
    let svg = decode(a.svg).trim();
    if (!svg.startsWith("<svg") || !svg.includes("viewBox")) {
      rejected++;
      continue;
    }
    const lower = svg.toLowerCase();
    if (BANNED.some((b) => lower.includes(b))) {
      rejected++;
      continue;
    }
    if (seen.has(a.key)) continue;
    // Ensure it fills its wrapper (square viewBox + square wrapper).
    if (!/<svg[^>]*\bwidth=/.test(svg)) {
      svg = svg.replace("<svg", '<svg width="100%" height="100%"');
    }
    seen.add(a.key);
    list.push({ key: a.key, label: a.label });
    map[a.key] = svg;
  }
}

const header = `// AUTO-GENERATED by scripts/gen-avatars.mjs - do not edit by hand.
// ${list.length} original SVG character avatars for personalities.

export const PERSONALITY_AVATARS = ${JSON.stringify(list, null, 2)} as const;

export type PersonalityAvatarKey = (typeof PERSONALITY_AVATARS)[number]["key"];

export const DEFAULT_AVATAR_KEY = ${JSON.stringify(list[0]?.key ?? "")};

export const AVATAR_SVGS: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;

writeFileSync(OUT, header);
console.log(`Wrote ${list.length} avatars to ${OUT} (rejected ${rejected}).`);
console.log("Keys:", list.map((a) => a.key).join(", "));
